# Generated by Django 2.0.5 on 2018-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='date_saida',
            field=models.DateField(null=True, verbose_name='Data da baixa'),
        ),
    ]
